name: Docker Image CI

on: [push]

env:
  DOCKER_IMAGE: bromine0x23/password-generator

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_IMAGE:$(date +%s)
